### ISSUE TITLE
Error when running `tallynn nanopore config`

### ISSUE THREAD

**Issue by yangao07** [Acribbs/TallyNN#5]
Hi,
I was trying to run tallynn on the scCOLOR datasets downloaded from SRA.
I met the following error:
```
$ tallynn nanopore config -v5

# 2021-07-16 04:59:13,889 INFO pipeline log is pipeline.log
# 2021-07-16 04:59:13,889 INFO output generated by nanopore config -v5 \
#                              job started at Fri Jul 16 04:59:13 2021 on m-4-01 -- bbcbf716-f7f3-44be-bcb1-14ebb8a62492 \
#                              pid: 1637105, system: Linux 4.18.0-193.28.1.el8_2.x86_64 #1 SMP Fri Oct 16 13:38:49 EDT 2020 x86_64
# 2021-07-16 04:59:13,889 INFO always_mount                            : False \
#                              cluster_memory_default                  : unlimited \
#                              cluster_memory_resource                 : None \
#                              cluster_num_jobs                        : None \
#                              cluster_options                         : None \
#                              cluster_parallel_environment            : None \
#                              cluster_priority                        : None \
#                              cluster_queue                           : None \
#                              cluster_queue_manager                   : sge \
#                              config_file                             : pipeline.yml \
#                              debug                                   : False \
#                              dry_run                                 : False \
#                              engine                                  : local \
#                              exceptions_terminate_immediately        : None \
#                              force_run                               : False \
#                              input_globs                             : [] \
#                              input_validation                        : False \
#                              is_test                                 : False \
#                              log_config_filename                     : None \
#                              log_exceptions                          : True \
#                              loglevel                                : 5 \
#                              multiprocess                            : None \
#                              only_info                               : False \
#                              pipeline_action                         : None \
#                              pipeline_format                         : svg \
#                              pipeline_logfile                        : pipeline.log \
#                              pipeline_targets                        : [] \
#                              random_seed                             : None \
#                              ruffus_checksums_level                  : 0 \
#                              shell_logfile                           : None \
#                              short_help                              : None \
#                              stderr                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'> \
#                              stdin                                   : <_io.TextIOWrapper name='<stdin>' mode='r' encoding='UTF-8'> \
#                              stdlog                                  : <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'> \
#                              stdout                                  : <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'> \
#                              terminate                               : None \
#                              timeit_file                             : None \
#                              timeit_header                           : None \
#                              timeit_name                             : all \
#                              tracing                                 : None \
#                              variables_to_set                        : [] \
#                              without_cluster                         : False \
#                              work_dir                                : None
# 2021-07-16 04:59:13,889 INFO started in directory: /scr1/users/gaoy1/sclong/scCOLOR/test
# 2021-07-16 04:59:13,936 INFO code location: /home/gaoy1/software/miniconda3/envs/tallynn/lib/python3.7/site-packages/cgatcore/pipeline
# 2021-07-16 04:59:13,936 INFO code version: 
# 2021-07-16 04:59:13,936 INFO working directory is: /scr1/users/gaoy1/sclong/scCOLOR/test
# 2021-07-16 04:59:13,936 INFO changing directory to /scr1/users/gaoy1/sclong/scCOLOR/test
# 2021-07-16 04:59:13,936 INFO pipeline has been initialized
# 2021-07-16 04:59:13,936 DEBUG starting run_workflow with action config
# 2021-07-16 04:59:13,936 INFO temporary directory is /tmp/gaoy1
Traceback (most recent call last):
  File "/home/gaoy1/software/miniconda3/envs/tallynn/bin/tallynn", line 33, in <module>
    sys.exit(load_entry_point('tallynn==0.0.1', 'console_scripts', 'tallynn')())
  File "/home/gaoy1/software/miniconda3/envs/tallynn/lib/python3.7/site-packages/tallynn-0.0.1-py3.7.egg/tallynn/entry.py", line 92, in main
    module.main(sys.argv)
  File "/home/gaoy1/software/miniconda3/envs/tallynn/lib/python3.7/site-packages/tallynn-0.0.1-py3.7.egg/tallynn/pipeline_nanopore.py", line 628, in main
    P.main(argv)
  File "/home/gaoy1/software/miniconda3/envs/tallynn/lib/python3.7/site-packages/cgatcore/pipeline/control.py", line 1498, in main
    run_workflow(args)
  File "/home/gaoy1/software/miniconda3/envs/tallynn/lib/python3.7/site-packages/cgatcore/pipeline/control.py", line 1452, in run_workflow
    write_config_files(pipeline_path, general_path)
  File "/home/gaoy1/software/miniconda3/envs/tallynn/lib/python3.7/site-packages/cgatcore/pipeline/control.py", line 129, in write_config_files
    (config_files, paths))
ValueError: default config file `['pipeline.yml']` not found in ['/home/gaoy1/software/miniconda3/envs/tallynn/lib/python3.7/site-packages/tallynn-0.0.1-py3.7.egg/tallynn/pipeline_nanopore', '/home/gaoy1/software/miniconda3/envs/tallynn/lib/python3.7/site-packages/tallynn-0.0.1-py3.7.egg/tallynn/configuration']
```
Any comments will be appreciated!
Thanks!

Yan

**Comment by Acribbs** [comment]
Hi Yan,

I actually can't work out why your pipeline.yml hasn't been included within your installation. It works no problem for me on my system following python setup.py develop. 

Unfortunately I am on holiday at the moment so can't really looking into this at the moment, but will do when I return.

Adam
